#! /bin/sh
### BEGIN INIT INFO
# Provides:          uppercase-service
# Required-Start:
# Required-Stop:
# Should-Start:
# Should-Stop:
# X-Start-Before:
# X-Stop-After:
# Default-Start:	3
# Default-Stop:
### END INIT INFO

PATH=/sbin:/bin:/usr/bin:/usr/local/sbin

. /lib/lsb/init-functions

do_start () {
	log_action_msg "Starting uppercase-service"
	nodejs /usr/local/sbin/serv.js &
}

do_stop () {
	log_action_msg "Stopping uppercase-service"
	kill -KILL `ps wwwaux | grep '/sbin/serv.js' | head -1 | awk '{print $2}'`
}

case "$1" in
  start)
	do_start
	exit 0
	;;
  stop)
	do_stop
	exit 0
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
